global:
  resolve_timeout: 5m
  # dingtalk_group_token:
  #   'xxx': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'
  #receiver: 'dingtalk.test'

receivers:
- name: 'web.hook'
  webhook_configs:
  - url: 'http://127.0.0.1:5001/'

# - name: 'dingtalk.test'
#   dingtalk_configs:
#   - group: 'xxx'
#     content: '{{ template "dingtalk.content" . }}'

# templates:
#   - '~/alertmanager/template/dingtalk.tmpl'
    
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
